# Generated by Django 5.2.8 on 2025-11-12 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='folio', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='foliolineitem',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.folio'),
        ),
        migrations.AddField(
            model_name='payment',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.folio'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paystacktransaction',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_transaction', to='billing.payment'),
        ),
    ]
