# Generated by Django 5.2.8 on 2025-11-12 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('occupancy', 'Occupancy Analysis'), ('revenue', 'Revenue Forecast'), ('guest_insights', 'Guest Insights'), ('trends', 'Booking Trends'), ('recommendations', 'Smart Recommendations')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('data', models.JSONField()),
                ('insights', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(default='AI Analytics Engine', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_rooms', models.IntegerField()),
                ('occupied_rooms', models.IntegerField()),
                ('available_rooms', models.IntegerField()),
                ('occupancy_rate', models.FloatField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('guest_count', models.IntegerField()),
                ('check_ins', models.IntegerField()),
                ('check_outs', models.IntegerField()),
                ('cancellations', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
